// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVtaW8BANmTQoZnX_CIA15bxzR8n_slk',
    appId: '1:245690992483:web:b7c76749b9f5b06ecab556',
    messagingSenderId: '245690992483',
    projectId: 'expanse-979cb',
    authDomain: 'expanse-979cb.firebaseapp.com',
    storageBucket: 'expanse-979cb.firebasestorage.app',
    measurementId: 'G-C089W5HF68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmKyz3bU13yEXS4myXpw9ZVqjIShCPd7k',
    appId: '1:245690992483:android:8aa40882807ca596cab556',
    messagingSenderId: '245690992483',
    projectId: 'expanse-979cb',
    storageBucket: 'expanse-979cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw9GFtaKWW4xcMcV6DxCXJFKCJoKKkFWk',
    appId: '1:245690992483:ios:07b75b036a31b94fcab556',
    messagingSenderId: '245690992483',
    projectId: 'expanse-979cb',
    storageBucket: 'expanse-979cb.firebasestorage.app',
    iosBundleId: 'com.example.expanseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw9GFtaKWW4xcMcV6DxCXJFKCJoKKkFWk',
    appId: '1:245690992483:ios:07b75b036a31b94fcab556',
    messagingSenderId: '245690992483',
    projectId: 'expanse-979cb',
    storageBucket: 'expanse-979cb.firebasestorage.app',
    iosBundleId: 'com.example.expanseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbVtaW8BANmTQoZnX_CIA15bxzR8n_slk',
    appId: '1:245690992483:web:8a7b9ff3f39b28c6cab556',
    messagingSenderId: '245690992483',
    projectId: 'expanse-979cb',
    authDomain: 'expanse-979cb.firebaseapp.com',
    storageBucket: 'expanse-979cb.firebasestorage.app',
    measurementId: 'G-01BCBPXN2M',
  );
}
